name: release-chart

on:
  push:
    tags: [helm-v**]

jobs:
  release-chart:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - shell: bash
        run: tar -zcvf "storage-local-static-provisioner-${GITHUB_REF#refs/tags/}.tgz" -C helm/provisioner .
      - run: git checkout pages
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm repo index --url "https://flachesis.github.io/sig-storage-local-static-provisioner" .
      - shell: bash
        run: |
          git add .
          git config --local user.email "github-actions-bot@users.noreply.github.com"
          git config --local user.name "github-actions-bot"
          git commit -m "release ${GITHUB_REF#refs/tags/}"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: pages
